name: Test CI/CD

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Setup JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test